name: Bump TiFlash Proxy

on:
  workflow_dispatch:
    inputs:
      proxy_commit:
        description: "Update to this TiFlash Proxy commit hash"
        required: true

jobs:
  bump-proxy:
    runs-on:
      - self-hosted
      - serverless
      - X64
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GIT_ACTION_BOT }}
          fetch-depth: 0
          clean: false

      - name: Update tiflash-proxy submodule
        run: |
          cd contrib/tiflash-proxy
          git fetch origin
          git checkout ${{ github.event.inputs.proxy_commit }}
          cd ../..
          git add contrib/tiflash-proxy

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          commit-message: "proxy: Bump to ${{ github.event.inputs.proxy_commit }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: "bump-proxy/${{ github.event.inputs.proxy_commit }}"
          delete-branch: true
          assignees: ${{ github.actor }}
          title: "proxy: Bump to ${{ github.event.inputs.proxy_commit }}"
          body: |
            Update proxy to https://github.com/tidbcloud/cloud-storage-engine/commits/${{ github.event.inputs.proxy_commit }}"

            This PR is triggered by:
            - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - ${{ github.actor }}
          labels: |
            automated pr

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Approve the PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GIT_ACTION_BOT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
